#!/bin/bash

# Install chafa
mkdir -p ~/.local/bin
curl https://hpjansson.org/chafa/releases/static/chafa-1.8.0-1-x86_64-linux-gnu.tar.gz | tar -xzvf - chafa-1.8.0-1-x86_64-linux-gnu/chafa-linux-x86_64 -O > ~/.local/bin/chafa
chmod +x ~/.local/bin/chafa

# Install euporie-binder
pip install .

# Install binder
git clone https://github.com/joouha/euporie.git
pip install './euporie[all]'
